
POLYGON_RETRY_LIMIT: int = 2

INTRADAY_PATH: str = 'data/intraday'
DAY_PATH: str = 'data/day'
MARKET_PATH: str = 'data/market'
GENERIC_PATH: str = 'data/generic'

POLYGON_API_KEY_ENVNAME: str = 'POLYGON_API_KEY'
TDA_TOKEN_PATH_ENVNAME: str = 'TDA_TOKEN_PATH'
TDA_API_KEY_ENVNAME: str = 'TDA_API_KEY'
TDA_REDIRECT_URI_ENVNAME: str = 'TDA_REDIRECT_URI'
TDA_ACCOUNT_ID_ENVNAME: str = 'TDA_ACCOUNT_ID'
