
FINVIZ_REQUEST_INTERVAL: float = 1.
FINVIZ_MAX_REQUESTS_PER_INTERVAL: int = 4
FINVIZ_FETCH_RETRY_LIMIT: int = 2

POLYGON_API_KEY_ENVNAME: str = 'POLYGON_API_KEY'
POLYGON_REQUEST_INTERVAL: float = 12.
POLYGON_MAX_REQUESTS_PER_INTERVAL: int = 1
POLYGON_FETCH_RETRY_LIMIT: int = 3

TDA_TOKEN_PATH_ENVNAME: str = 'TDA_TOKEN_PATH'
TDA_API_KEY_ENVNAME: str = 'TDA_API_KEY'
TDA_REDIRECT_URI_ENVNAME: str = 'TDA_REDIRECT_URI'
TDA_ACCOUNT_ID_ENVNAME: str = 'TDA_ACCOUNT_ID'
TDA_REQUEST_INTERVAL: float = 1.
TDA_MAX_REQUESTS_PER_INTERVAL: int = 2
TDA_FETCH_RETRY_LIMIT: int = 3
TDA_MAX_REALTIME_SYMBOLS: int = 300

DEFAULT_TRADE_BUFFER_SIZE: int = 100000000
